spring.application.name=core-app
server.port = 7803

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel-booking-db
spring.datasource.username=postgres
spring.datasource.password=Sanket123
spring.jpa.hibernate.ddl-auto=update

# Tell Hibernate you're using PostgreSQL (avoids dialect warnings)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional but useful: see the actual SQL being fired during dev
spring.jpa.show-sql=true
